services:
  postgres-db:
    container_name: policia_db
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - policia-pg-data:/var/lib/postgresql/data

volumes:
  policia-pg-data: